### ISSUE TITLE
Deprecated array.prototype.flatten

### ISSUE THREAD

**Issue by contactjavas** [airbnb/browser-shims#19]
Versions
----
`Platform` version: Windows 10
`Node` version: 10.1.0
`NPM` version: 6.1.0
`airbnb-browser-shims` version: 2.1.0

What i did:
----
`npm i -S airbnb-browser-shims`

What i got:
----
Installed successfully with *deprecated warning*:
```
npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN airbnb@1.0.0 No repository field.
```

**Comment by ljharb** [comment]
Yep, that’s intentional. Warnings are always safe to ignore.

The next semver-major will drop it.

**Comment by ljharb** [comment]
v2.0.0 of airbnb-js-shims, and v3.0.0 of airbnb-browser-shims, are released.
