### ISSUE TITLE
TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by dclowd9901** [airbnb/browser-shims#20]
airbnb-browser-shims version: ^2.1.0
Jest Version: ^21.2.1

This seems to be an issue with browser shims' compatibility with `jsdom`. A simple reconstruction of this issue would be to create a test file:

```
/* testfile.test.jsx */

/**
 * @jest-environment jsdom
 */

import 'airbnb-browser-shims';

describe('any test', () => {
  it('should do something', () => {
    console.log('it will fail before tests are run');
  });
});
```
This throws an error: 
```
  ● Test suite failed to run

    TypeError: Cannot read property 'parentNode' of undefined
      
      at node_modules/matchmedia-polyfill/matchMedia.js:18:15
      at Object.<anonymous> (node_modules/matchmedia-polyfill/matchMedia.js:46:2)
      at Object.<anonymous> (node_modules/airbnb-browser-shims/browser-only.js:27:3)
      at Object.<anonymous> (node_modules/airbnb-browser-shims/index.js:7:1)
      at Object.<anonymous> (tests/DirectionProvider_test.jsx:14:1)
      at next (native)
      at next (native)
```

**Comment by ljharb** [comment]
This seems fixed by https://github.com/paulirish/matchMedia.js/issues/82 / https://github.com/paulirish/matchMedia.js/pull/76

**Comment by ljharb** [comment]
v0.3.1 of matchmedia-polyfill has been released; does that resolve your issue?

**Comment by ljharb** [comment]
ok now v0.3.1 is published, and i've confirmed that fixes the issue with jest.

2e55420a519c55c8034f376226795359d464b392 forces the update, but the semver range already includes it, so this should be automatic with a reinstall.
